name: Sync from upstream
on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch: {}      # allow manual runs too
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream & fetch
        run: |
          # set your upstream; public upstreams can be fetched anonymously
          git remote add upstream https://github.com/finnw/Credit-Card-Customers.git || true
          git fetch upstream --prune

      - name: Sync branches
        run: |
          # list branches you want to keep in sync
          BRANCHES="main"
          for BR in $BRANCHES; do
            # create local branch if missing
            git show-ref --verify --quiet refs/heads/$BR || git branch $BR origin/$BR || true
            git checkout $BR
            # fast-forward if possible; fall back to rebase
            git merge --ff-only upstream/$BR || git rebase upstream/$BR
            git push origin $BR
          done
